/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#360f00",
        "on-surface": "#111c2d",
        "on-surface-variant": "#434655",
        "surface-container-high": "#dee8ff",
        "inverse-primary": "#b4c5ff",
        "outline": "#737686",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#6063ee",
        "surface-dim": "#cfdaf2",
        "on-tertiary-fixed-variant": "#7d2d00",
        "inverse-surface": "#263143",
        "on-primary": "#ffffff",
        "surface-tint": "#0053db",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed": "#ffdbcd",
        "outline-variant": "#c3c6d7",
        "on-error-container": "#93000a",
        "background": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "primary-container": "#2563eb",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#bc4800",
        "secondary": "#4648d4",
        "primary-fixed-dim": "#b4c5ff",
        "primary": "#004ac6",
        "surface": "#f9f9ff",
        "surface-variant": "#d8e3fb",
        "error": "#ba1a1a",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed": "#07006c",
        "surface-container-highest": "#d8e3fb",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-container": "#ffede6",
        "on-secondary": "#ffffff",
        "tertiary": "#943700",
        "surface-container": "#e7eeff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-background": "#111c2d",
        "inverse-on-surface": "#ecf1ff",
        "dark-bg": "#0b121e",
        "dark-surface": "#161f2e",
        "dark-surface-bright": "#1e293b",
        "on-dark-surface": "#f1f5f9",
        "on-dark-surface-variant": "#94a3b8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1200px",
        "lg": "24px",
        "md": "16px",
        "xl": "32px",
        "sm": "12px",
        "2xl": "48px",
        "gutter": "20px",
        "xs": "8px",
        "base": "4px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      },
      maxWidth: {
        "container-max": "1200px",
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
